source 'https://rubygems.org'
ruby '2.2.0'

gem 'sinatra'
gem 'sinatra-partial'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'
gem 'bcrypt'
gem 'rack-flash3'
gem 'rspec'
gem 'cucumber'
gem 'rubocop-rspec'
gem 'rubocop'
gem 'capybara'
gem 'pg'
gem 'restclient'
